# enable automatic reload of tmux config
bind r source-file ~/.tmux.conf

# remap tmux prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# remap pane split keys
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.config/tmux/tmux.conf

# remove confirmation to kill pane/window
bind-key x kill-pane
bind-key & kill-window

# speed up pane-switching panes (alt-arrow, no prefix)
bind -n M-left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# allow for mouse mode
set -g mouse on

# force named windows
set-option -g allow-rename off

# CUSTOM TEMPLATE
# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# vim-like key bindings (activate via Ctrl+a [)
set-window-option -g mode-keys vi

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'thekylehuang/cole-tmux'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
